# MediaWiki with MariaDB
version: '3'
volumes:
  data-mariadb:
    external: true
  caddy-data:

services:
  mediawiki:
    image: ghcr.io/mchangrh/sb-wiki:1.39
    restart: always
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./settings/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./settings/secrets:/secrets:ro
      - ./settings/includes:/includes:ro
  database:
    image: mariadb:latest
    restart: always
    env_file:
      - ./db.env
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - data-mariadb:/var/lib/mysql
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - mediawiki
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    environment:
      EMAIL: "dev@ajay.app"
