services:
  mediawiki:
    container_name: mediawiki
    image: ghcr.io/mchangrh/sb-wiki:1.39
    restart: always
    ports:
      - 8080:80 # left open for debugging
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./settings/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./settings/secrets:/secrets:ro
      - ./settings/includes:/includes:ro
  database:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - ./db.env
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - data-mariadb:/var/lib/mysql
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - mediawiki
    env_file:
      - ./caddy.env
    volumes:
      - .caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - data-caddy:/data

version: '3'
volumes:
  data-mariadb:
    external: true
  data-caddy:
    external: true