# MediaWiki with MariaDB
version: '3'
volumes:
  data-mariadb:
    external: true

services:
  mediawiki:
    image: sb-wiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./settings/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./settings/secrets:/secrets:ro
      - ./settings/includes:/includes:ro
  database:
    image: mariadb:latest
    restart: always
    env_file:
      - ./db.env
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_RANDOM_ROOT_PASSWORD: TRUE
    volumes:
      - data-mariadb:/var/lib/mysql